import type { BrandKit } from "@/types";

export const TEAM_SKILL_DEFAULTS: Pick<
  BrandKit,
  | "product_terms"
  | "risky_words"
  | "preferred_wording"
  | "missing_tone_map"
  | "wrong_tone_map"
  | "ambiguous_words"
> = {
  product_terms: {
    vnggames: "VNGGames",
    "vng games": "VNGGames",
    "VNG Games": "VNGGames",
    VNGgames: "VNGGames",
    "zingplay game studios": "ZingPlay Game Studios",
    zingplay: "ZingPlay",
    "ZingPlay game studios": "ZingPlay Game Studios",
    zingmp3: "ZingMP3",
    "zing mp3": "ZingMP3",
    ZingMp3: "ZingMP3",
    "zing Mp3": "ZingMP3",
    kiki: "KiKi",
    KiKI: "KiKi",
    KIKI: "KiKi",
    zalopay: "Zalopay",
    "zalo pay": "Zalopay",
    ZaloPay: "Zalopay",
    ZaloPAY: "Zalopay",
    ZALOPAY: "Zalopay",
    greennode: "GreenNode",
    "green node": "GreenNode",
    GreenNODE: "GreenNode",
    GREENNODE: "GreenNode",
    zalo: "Zalo",
    ZALO: "Zalo",
    zing: "Zing",
    ZING: "Zing",
  },
  risky_words: {
    "lừa đảo": {
      priority: "high",
      suggestion: "Dùng cách diễn đạt trung lập hơn, tránh gây hiểu lầm về thương hiệu.",
    },
    "sập app": {
      priority: "high",
      suggestion: "Chỉ dùng trong thông báo kỹ thuật chính thức, không dùng trên mạng xã hội.",
    },
    "lỗi hệ thống": {
      priority: "high",
      suggestion: "Dùng 'bảo trì hệ thống' hoặc 'nâng cấp dịch vụ' thay thế.",
    },
    "bug đầy": {
      priority: "medium",
      suggestion: "Cần tối ưu thêm / đang được cải thiện.",
    },
    toang: {
      priority: "medium",
      suggestion: "Gặp sự cố / cần được xử lý.",
    },
    "tệ quá": {
      priority: "medium",
      suggestion: "Dùng cách diễn đạt mang tính xây dựng hơn.",
    },
    "dở hơi": {
      priority: "high",
      suggestion: "Tránh dùng ngôn từ xúc phạm trong truyền thông thương hiệu.",
    },
    "vô dụng": {
      priority: "high",
      suggestion: "Tránh dùng ngôn từ tiêu cực về sản phẩm/dịch vụ.",
    },
    "thất bại": {
      priority: "medium",
      suggestion: "Dùng 'chưa đạt mục tiêu' hoặc 'cần cải thiện' thay thế.",
    },
    "phá sản": {
      priority: "high",
      suggestion: "Không dùng từ ngữ gây hoang mang về tình hình tài chính.",
    },
  },
  preferred_wording: {
    "xịn sò": "nổi bật",
    "siêu xịn": "ấn tượng",
    "lụm ngay": "khám phá ngay",
    "đỉnh của chóp": "ấn tượng",
    "hết nước chấm": "rất ấn tượng",
    "chất lừ": "chất lượng cao",
    "thần thánh": "xuất sắc",
    "bá đạo": "vượt trội",
    "cực phẩm": "sản phẩm cao cấp",
    "quá đỉnh": "rất ấn tượng",
    "ngon lành": "tuyệt vời",
    "mlem mlem": "hấp dẫn",
    "oke lá cờ": "đồng ý",
    "chắc kèo": "chắc chắn",
    "auto đăng ký": "đăng ký ngay",
    "xịn xò": "nổi bật",
  },
  missing_tone_map: {
    khong: "không",
    duoc: "được",
    "nguoi dung": "người dùng",
    "cong nghe": "công nghệ",
    "trai nghiem": "trải nghiệm",
    "san pham": "sản phẩm",
    "ket noi": "kết nối",
    "dong hanh": "đồng hành",
    "no luc": "nỗ lực",
    "phat trien": "phát triển",
    "luon luon": "luôn luôn",
    "thong tin": "thông tin",
    "giai phap": "giải pháp",
    "tinh nang": "tính năng",
    "nang cao": "nâng cao",
    "ho tro": "hỗ trợ",
    "tuong lai": "tương lai",
    "cuoc song": "cuộc sống",
    "mang lai": "mang lại",
    "hop tac": "hợp tác",
    "chinh sach": "chính sách",
    "dich vu": "dịch vụ",
    "ung dung": "ứng dụng",
    "su kien": "sự kiện",
    "khach hang": "khách hàng",
    "cong dong": "cộng đồng",
    "bao mat": "bảo mật",
    "toc do": "tốc độ",
    "hieu qua": "hiệu quả",
    "thuc hien": "thực hiện",
  },
  wrong_tone_map: {
    "hổ trợ": "hỗ trợ",
    "trãi nghiệm": "trải nghiệm",
    "chia sẽ": "chia sẻ",
    "sữa lỗi": "sửa lỗi",
    "xữ lý": "xử lý",
    "dử liệu": "dữ liệu",
    "nổ lực": "nỗ lực",
    "xãy ra": "xảy ra",
    phãi: "phải",
    chĩnh: "chỉnh",
    "sẵn sàn": "sẵn sàng",
    "khoẻ mạnh": "khỏe mạnh",
    "mạnh mẻ": "mạnh mẽ",
    "thỏa mãng": "thỏa mãn",
    "nổi bậc": "nổi bật",
    "hưỡng dẫn": "hướng dẫn",
    tuỡng: "tưởng",
    chuẫn: "chuẩn",
  },
  ambiguous_words: {
    ban: ["bạn", "bàn", "bán"],
    co: ["có", "cô", "cỏ"],
    bo: ["bộ", "bố", "bò"],
    nam: ["năm", "nam", "nắm"],
    la: ["là", "lá", "lạ"],
    ma: ["mà", "má", "ma"],
    ba: ["ba", "bà", "bá"],
    ca: ["ca", "cá", "cà"],
    da: ["da", "dạ", "dá"],
    dau: ["đâu", "đầu", "dâu"],
    den: ["đến", "đen", "đèn"],
    di: ["đi", "dì", "dị"],
    do: ["do", "đó", "đô"],
    ga: ["ga", "gà", "gá"],
    go: ["gỗ", "gò", "gõ"],
    ha: ["hạ", "há", "hà"],
    ho: ["họ", "hồ", "hô"],
    ke: ["kể", "kê", "kẻ"],
    lo: ["lo", "lò", "lỗ"],
    lua: ["lúa", "lửa", "lụa"],
    mua: ["mua", "mùa", "múa"],
    nha: ["nhà", "nhá", "nhạ"],
    ta: ["ta", "tà", "tá"],
    tho: ["thơ", "thổ", "thọ"],
    thu: ["thư", "thú", "thủ"],
    tua: ["tua", "túa", "tụa"],
    va: ["và", "vá", "vạ"],
    vo: ["vợ", "vố", "vô"],
    xe: ["xe", "xé", "xẽ"],
    xua: ["xưa", "xua", "xúa"],
  },
};
